version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: bike
      POSTGRES_PASSWORD: bike
      POSTGRES_DB: bikesegura
    ports:
      - "5431:5432" # host:container (5432 é a porta interna padrão do Postgres)
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    command: flask run --host=0.0.0.0 --port=8000 --debug
    env_file:
      - .env
    environment:
      - FLASK_APP=manage.py
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=bikesegura
      - DB_USER=bike
      - DB_PASSWORD=bike
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
